name: ACC Release sample

on:
  push:
    branches:
      - release/**
  workflow_dispatch:

jobs:
  update-release-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Update .release
        run: |
          FILE="./.github/workflows/.release"
          CURRENT_VERSION=$(cat $FILE)
          NEXT_VERSION=$((CURRENT_VERSION + 1))
          echo "$NEXT_VERSION" > $FILE
          echo "Next version is $NEXT_VERSION"

      - name: Commit changes
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/.release
          git commit -m "Increment release version"
          git push
