name: ACC Release sample

on:
  push:
    branches:
      - release/**
  workflow_dispatch:

jobs:
  update-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Update .release
        run: |
          ./update-release.sh
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/.release
          git commit -m "Increment release version"
          git push
