name: Cache

on: pull_request

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: test-${{ runner.os }}-${{ github.sha }} # キャッシュのキーを指定
          path: ${{ github.workspace }}/dummy # キャッシュ対象のディレクトリを指定
          restore-keys: | # キャッシュが見つからなかった場合に使用するキーを指定、キーに一致するキャッシュが見つからない場合、restore-keyのprefixが一致するキャッシュを探す
            test-${{ runner.os }}-
      - run: |
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then exit 0; fi
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 30
      - run: ls -lh "${GITHUB_WORKSPACE}/dummy"

# キャッシュのルール
# 7日以上アクセスされていないキャッシュは削除
# キャッシュの合計サイズは各リポジトリ10Gまで
