name: Schedule
on:
  # schedule:
  #   - cron: '*/15 * * * *' # 15分毎に実行
  push:
    branches-ignore:
      - '**'
jobs: 
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
